services:
  schoolerp:
    build: .
    container_name: schoolerp

    mem_limit: 1g
    cpus: "1.0"

    command: >
      gunicorn
      --workers 4
      --bind 0.0.0.0:5000
      --timeout 120
      --access-logfile -
      --error-logfile -
      app:app

    env_file:
      - .env

    restart: unless-stopped

    networks:
      - advthakre_techsora-net

    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:5000/healthcheck"]
      interval: 30s
      timeout: 10s
      retries: 3

networks:
  advthakre_techsora-net:
    external: true